### ISSUE TITLE
无法正常在 Actions 使用

### ISSUE THREAD

**Issue by vlssu** [renbaoshuo/deploy-certificate-to-tencentcloud#2]
https://github.com/vlssu/docs-vlssu/runs/8054351534?check_suite_focus=true#step:5:25
这是运行后的报错

**Comment by renbaoshuo** [comment]
https://github.com/vlssu/docs-vlssu/blob/065b4c7f7fed6091fab2533aa70a5f14424efc65/.github/workflows/qcloud-cdn.yml#L28-L31

您的配置有误，请仔细查看说明。
